# **NLP Tutorial: Text Representation - Bag Of Words (BOW)**

In [69]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_csv("/content/drive/MyDrive/NLP Notes/MY NLP/2. Text Representation (Text Vectrozition)/1. Bag Of Words/spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [71]:
df.Category.value_counts()

,count
Category,
ham,4825
spam,747


In [72]:
df["spam"] = df["Category"].apply(lambda x: 1 if x == 'spam' else 0 )

In [73]:
df.head(5)

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [74]:
df.shape

(5572, 3)

# Train test split

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [76]:
X_train

,Message
1500,"SMS. ac JSco: Energy is high, but u may not kn..."
3228,Wife.how she knew the time of murder exactly
3732,Isn't frnd a necesity in life? imagine urself ...
1781,BIG BROTHER ALERT! The computer has selected u...
5511,"It‘s reassuring, in this crazy world."
...,...
4034,I am taking you for italian food. How about a ...
1143,Have you had a good day? Mine was really busy ...
643,Probably gonna swing by in a wee bit
124,I am going to sao mu today. Will be done only ...


In [77]:
X_train.shape

(4457,)

In [78]:
X_test

,Message
252,"Wen ur lovable bcums angry wid u, dnt take it ..."
1523,I thk u dun haf 2 hint in e forum already lor....
5278,URGENT! Your Mobile number has been awarded wi...
3526,I not free today i haf 2 pick my parents up to...
3813,Yep then is fine 7.30 or 8.30 for ice age.
...,...
214,Yup... How ü noe leh...
2297,<Forwarded from 21870000>Hi - this is your Mai...
4137,have you ever had one foot before?
340,U calling me right? Call my hand phone...


In [79]:
X_test.shape

(1115,)

In [80]:
type(X_train)

pandas.core.series.Series

In [81]:
X_train[:4]

,Message
1500,"SMS. ac JSco: Energy is high, but u may not kn..."
3228,Wife.how she knew the time of murder exactly
3732,Isn't frnd a necesity in life? imagine urself ...
1781,BIG BROTHER ALERT! The computer has selected u...


In [82]:
type(X_train.values)

numpy.ndarray


# **Create bag of words representation using CountVectorizer**

In [125]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()


X_train_cv = v.fit_transform(X_train.values)
X_train_cv


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58739 stored elements and shape (4457, 7691)>

In [126]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [127]:
X_train_cv.shape

(4457, 7691)

In [132]:
v.get_feature_names_out()[1771]

'chinatown'

In [133]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',


In [131]:
v.vocabulary_

{'sms': 6223,
 'ac': 758,
 'jsco': 3838,
 'energy': 2564,
 'is': 3727,
 'high': 3407,
 'but': 1555,
 'may': 4373,
 'not': 4805,
 'know': 3943,
 'where': 7429,
 '2channel': 377,
 'it': 3738,
 '2day': 378,
 'ur': 7145,
 'leadership': 4035,
 'skills': 6162,
 'strong': 6484,
 'psychic': 5448,
 'reply': 5673,
 'ans': 970,
 'question': 5490,
 'end': 2556,
 'wife': 7456,
 'how': 3496,
 'she': 6037,
 'knew': 3940,
 'the': 6769,
 'time': 6853,
 'of': 4859,
 'murder': 4634,
 'exactly': 2665,
 'isn': 3734,
 'frnd': 2992,
 'necesity': 4705,
 'in': 3617,
 'life': 4081,
 'imagine': 3594,
 'urself': 7158,
 'witout': 7501,
 'hw': 3546,
 'feel': 2781,
 'at': 1107,
 'colleg': 1875,
 'wat': 7337,
 'll': 4140,
 'do': 2354,
 'wth': 7580,
 'cell': 1684,
 'abt': 753,
 'functions': 3021,
 'thnk': 6810,
 'events': 2636,
 'espe': 2615,
 'cared': 1634,
 'missed': 4488,
 'amp': 936,
 'irritated': 3722,
 '4wrd': 519,
 'to': 6885,
 'all': 898,
 'those': 6814,
 'dear': 2171,
 'loving': 4215,
 'frnds': 2993,
 'wthout

In [117]:
X_train_cv[0]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 23 stored elements and shape (1, 7691)>

In [99]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [100]:
np.where(X_train_np[0]!=0)

(array([ 377,  378,  758,  970, 1555, 2556, 2564, 3407, 3727, 3738, 3838,
        3943, 4035, 4373, 4805, 5448, 5490, 5673, 6162, 6223, 6484, 7145,
        7429]),)

In [119]:
X_train[:4][1500]

'SMS. ac JSco: Energy is high, but u may not know where 2channel it. 2day ur leadership skills r strong. Psychic? Reply ANS w/question. End? Reply END JSCO'

In [120]:
X_train_np[0][377]

np.int64(1)


# **Train the naive bayes model**

In [121]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

 **In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.**
**On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.**

In [134]:
X_test_cv = v.transform(X_test)


# **Evaluate Performance**

In [124]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       965
           1       0.98      0.96      0.97       150

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [136]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])


# **Train the model using sklearn pipeline and reduce number of lines of code**

In [137]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [138]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [139]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       965
           1       0.98      0.96      0.97       150

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

